Fix python3 test failures
The test was raising an exception due to changes between python2 and 3
with the buffer API:

TypeError: Type str doesn't support the buffer API