Disallow werkzeug>=1.0
Due to depracation of top level imports (https://github.com/pallets/werkzeug/commit/08536c457c7125c05e0947e62487fbc4bcf51717), e.g. `from werkzeug import secure_filename` won't work anymore:

```
File "/usr/local/lib/python3.7/site-packages/flask_admin/model/__init__.py", line 2, in <module>
from .base import BaseModelView
File "/usr/local/lib/python3.7/site-packages/flask_admin/model/base.py", line 8, in <module>
from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
```